# Generated by Django 4.2.3 on 2023-08-01 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bsn_card", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="details",
            name="category",
            field=models.CharField(default="", max_length=50),
        ),
    ]
