# Generated by Django 4.2.3 on 2023-08-05 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bsn_card", "0004_details_comment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="details",
            name="comment",
            field=models.CharField(default="", max_length=10000),
        ),
    ]
